### ISSUE TITLE
js-sandbox crate: build fails due to DNS resolution failure; no way to retry

### ISSUE THREAD

**Issue by Bromeon** [rust-lang/docs.rs#1074]
**Crate name:** js-sandbox
**Build failure link:** https://docs.rs/crate/js-sandbox/0.1.2/builds/300462

Edit: looks like the same happened to deno_core (https://docs.rs/crate/js-sandbox/0.1.2/builds/300462)

**Additional details:** Temporary DNS failure in a dependency (`rusty_v8`), there seems to be no way to retry the build later.
Interesting part of the build log:

```
[INFO] [stderr] error: failed to run custom build command for `rusty_v8 v0.10.0`
[INFO] [stderr] 
[INFO] [stderr] Caused by:
[INFO] [stderr]   process didn't exit successfully: `/opt/rustwide/target/debug/build/rusty_v8-3610e430cdc1443f/build-script-build` (exit code: 101)
[INFO] [stderr]   --- stdout
[INFO] [stderr]   static lib URL: https://github.com/denoland/rusty_v8/releases/download/v0.10.0/librusty_v8_debug_x86_64-unknown-linux-gnu.a
[INFO] [stderr]   cargo:rustc-link-search=/opt/rustwide/target/debug/gn_out/obj
[INFO] [stderr]   Downloading https://github.com/denoland/rusty_v8/releases/download/v0.10.0/librusty_v8_debug_x86_64-unknown-linux-gnu.a
[INFO] [stderr]   Downloading https://github.com/denoland/rusty_v8/releases/download/v0.10.0/librusty_v8_debug_x86_64-unknown-linux-gnu.a...
[INFO] [stderr]   <urlopen error [Errno -3] Temporary failure in name resolution>
[INFO] [stderr]   Retrying in 5 s ...
[INFO] [stderr]   Downloading https://github.com/denoland/rusty_v8/releases/download/v0.10.0/librusty_v8_debug_x86_64-unknown-linux-gnu.a...
[INFO] [stderr]   <urlopen error [Errno -3] Temporary failure in name resolution>
[INFO] [stderr]   Retrying in 10 s ...
[INFO] [stderr]   Downloading https://github.com/denoland/rusty_v8/releases/download/v0.10.0/librusty_v8_debug_x86_64-unknown-linux-gnu.a...
[INFO] [stderr]   <urlopen error [Errno -3] Temporary failure in name resolution>
[INFO] [stderr]   Retrying in 20 s ...
[INFO] [stderr]   Downloading https://github.com/denoland/rusty_v8/releases/download/v0.10.0/librusty_v8_debug_x86_64-unknown-linux-gnu.a...
[INFO] [stderr]   <urlopen error [Errno -3] Temporary failure in name resolution>
[INFO] [stderr]   Python downloader failed, trying with curl.
[INFO] [stderr] 
[INFO] [stderr]   --- stderr
[INFO] [stderr]   Traceback (most recent call last):
[INFO] [stderr]     File "./tools/download_file.py", line 64, in <module>
[INFO] [stderr]       sys.exit(main())
[INFO] [stderr]     File "./tools/download_file.py", line 59, in main
[INFO] [stderr]       DownloadUrl(args.url, f)
[INFO] [stderr]     File "./tools/download_file.py", line 45, in DownloadUrl
[INFO] [stderr]       raise e
[INFO] [stderr]   urllib2.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
[INFO] [stderr]   thread 'main' panicked at 'assertion failed: status.success()', /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.10.0/build.rs:230:3
[INFO] [stderr]   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[INFO] running `Command { std: "docker" "inspect" "9a305851b91453a19d640113d821c2ac97fb81fecd176be56e64cf1d2643ca5d", kill_on_drop: false }`
[INFO] running `Command { std: "docker" "rm" "-f" "9a305851b91453a19d640113d821c2ac97fb81fecd176be56e64cf1d2643ca5d", kill_on_drop: false }`
[INFO] [stdout] 9a305851b91453a19d640113d821c2ac97fb81fecd176be56e64cf1d2643ca5d
```

**Comment by Nemo157** [comment]
That's not a temporary failure, there is no network access from within the docs.rs build environment.

It appears that `rusty_v8` has a bypass for when _its_ documentation is being built: <https://github.com/denoland/rusty_v8/blob/master/build.rs#L13-L14>; you might be best asking for them to also detect the `DOCS_RS` environment variable (or providing some other way to bypass it) to allow building documentation for crates that depend on it (as documented in <https://docs.rs/about/builds#detecting-docsrs>).

**Comment by Bromeon** [comment]
Thank you!
After reporting the issue to the Deno devs, they fixed it in https://github.com/denoland/rusty_v8/pull/485.

[deno_core v0.62](https://docs.rs/deno_core/0.62.0) and [js-sandbox v0.1.3](https://docs.rs/js-sandbox/0.1.3/js_sandbox/), based on rusty_v8 v0.11.0, are again both documented.
