### ISSUE TITLE
Crate build failure: Deref section without derived id

### ISSUE THREAD

**Issue by ritchie46** [rust-lang/docs.rs#1265]
**Crate name:** Polars
**Build failure link:** https://docs.rs/crate/polars/0.12.0/builds/342455

**Additional details:**
Maybe this is related to https://github.com/rust-lang/rust/issues/81395 ? 

Below are the last lines of a run with `$ RUST_BACKTRACE=1 RUSTDOC_LOG=trace cargo doc`

```
INFO rustdoc::html::render Documenting ChunkedArray
INFO rustdoc::html::render Documenting associated items of Some("ChunkedArray")
thread 'rustc' panicked at 'Deref section without derived id', src/librustdoc/html/render/mod.rs:4418:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f4eb5d9f719cd3c849befc8914ad8ce0ddcf34ed/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/f4eb5d9f719cd3c849befc8914ad8ce0ddcf34ed/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/f4eb5d9f719cd3c849befc8914ad8ce0ddcf34ed/library/core/src/option.rs:1258:5
   3: rustdoc::html::render::sidebar_deref_methods
   4: rustdoc::html::render::sidebar_assoc_items
   5: rustdoc::html::render::print_sidebar
   6: rustdoc::html::layout::render
   7: rustdoc::html::render::Context::render_item
   8: <rustdoc::html::render::Context as rustdoc::formats::renderer::FormatRenderer>::item
   9: rustdoc::formats::renderer::run_format
  10: rustdoc::run_renderer
  11: rustc_session::utils::<impl rustc_session::session::Session>::time
  12: rustc_interface::passes::QueryContext::enter
  13: rustc_interface::interface::create_compiler_and_run
  14: rustdoc::main_options
  15: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

error: Unrecognized option: 'crate-version'

warning: 2 warnings emitted

error: could not document `polars`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type lib --crate-name polars polars/src/lib.rs -o /home/ritchie46/code/polars/target/doc --cfg 'feature="default"' --cfg 'feature="docs"' --cfg 'feature="lazy"' --cfg 'feature="parquet"' --cfg 'feature="simd"' --cfg 'feature="temporal"' --error-format=json --json=diagnostic-rendered-ansi -L dependency=/home/ritchie46/code/polars/target/debug/deps --extern polars_core=/home/ritchie46/code/polars/target/debug/deps/libpolars_core-d67fefc814cdb70a.rmeta --extern polars_io=/home/ritchie46/code/polars/target/debug/deps/libpolars_io-c2327cc5c1902172.rmeta --extern polars_lazy=/home/ritchie46/code/polars/target/debug/deps/libpolars_lazy-d49b632cd376ea9d.rmeta --crate-version 0.12.0` (exit code: 1)

```

**Comment by jryans** [comment]
Yes, it might be related to that Rust issue. I'll check this crate as part of testing the fix over there.

**Comment by jryans** [comment]
Indeed, https://github.com/rust-lang/rust/pull/81491 which fixes https://github.com/rust-lang/rust/issues/81395 also fixes this crate as well.

**Comment by Nemo157** [comment]
:+1: once that's in a new nightly someone can queue this crate to be rebuilt.

**Comment by jryans** [comment]
The 2021-02-01 nightly now contains a fix for this.

**Comment by jyn514** [comment]
I queued a rebuild, which failed with what seems like a legitimate error: https://docs.rs/crate/polars/0.12.0/builds/348675

```
[INFO] [stderr] error[E0599]: no method named `fold_first` found for struct `std::iter::FilterMap<std::slice::Iter<'_, &arrow::array::PrimitiveArray<T>>, [closure@/opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/polars-core-0.12.0/src/chunked_array/ops/aggregate.rs:119:29: 119:49]>` in the current scope
[INFO] [stderr]    --> /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/polars-core-0.12.0/src/chunked_array/ops/aggregate.rs:120:18
[INFO] [stderr]     |
[INFO] [stderr] 120 |                 .fold_first(|acc, v| if acc < v { acc } else { v }),
[INFO] [stderr]     |                  ^^^^^^^^^^ method not found in `std::iter::FilterMap<std::slice::Iter<'_, &arrow::array::PrimitiveArray<T>>, [closure@/opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/polars-core-0.12.0/src/chunked_array/ops/aggregate.rs:119:29: 119:49]>`
```
