### ISSUE TITLE
flaky test: storage::backend_tests::s3::test_store_all_in_archive

### ISSUE THREAD

**Issue by syphar** [rust-lang/docs.rs#2372]
likely a problem with our test config / test isolation. 

```
failures:

---- storage::backend_tests::s3::test_store_all_in_archive stdout ----
the test failed: database disk image is malformed
  caused by: database disk image is malformed
  caused by: Error code 11: The database disk image is malformed
   0: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1963:27
   1: docs_rs::storage::archive_index::find_in_sqlite_index
             at ./src/storage/archive_index.rs:76:20
   2: docs_rs::storage::archive_index::find_in_file
             at ./src/storage/archive_index.rs:110:5
   3: docs_rs::storage::AsyncStorage::exists_in_archive::{{closure}}::{{closure}}
             at ./src/storage/mod.rs:259:24
   4: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/thread/mod.rs:528:30
  29: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
  30: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys/unix/thread.rs:108:17
  31: <unknown>
  32: <unknown>

thread 'storage::backend_tests::s3::test_store_all_in_archive' panicked at src/storage/mod.rs:1298:5:
the test failed
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: docs_rs::test::wrapper
             at ./src/test/mod.rs:55:9
   3: docs_rs::storage::backend_tests::s3::test_store_all_in_archive
             at ./src/storage/mod.rs:1290:21
   4: docs_rs::storage::backend_tests::s3::test_store_all_in_archive::{{closure}}
             at ./src/storage/mod.rs:1289:27
   5: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by syphar** [comment]
seems fine now
