### ISSUE TITLE
Enable removal/access restriction for specific versions of a crate, rather than the entire crate

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/docs.rs#528]
Currently, [the way to remove crates](https://github.com/rust-lang/crates-io-cargo-teams/blob/master/docs/crate-removal-procedure.md#remove-relevant-versions-andor-entire-crates-from-docsrs) is to edit the nginx file and block the whole crate:

```
location /CRATENAME {
			return 410;
		}
		location /crate/CRATENAME {
			return 410;
		}
```

There are reasons for needing to take down some versions and not others, so docs.rs needs a way to do that.

Could it be as simple as doing this in the nginx config instead...?

```
location /CRATENAME/VERSION {
    return 410;
}
```

@pietroalbini I know you already know about this, but I wanted an issue for tracking and I couldn't find an existing one.

**Comment by pietroalbini** [comment]
I'm working on a command like this:

```
cratesfyi database remove-crate CRATENAME
```

...which properly removes the crate from the database and from S3, so the nginx stuff isn't required anymore.

**Comment by jyn514** [comment]
@pietroalbini delete-crate was a good first step, but I think it only allowed removing the entire crate, not a specific version.  I think this issue should be kept open until we add that functionality.

**Comment by jyn514** [comment]
#893 did not actually work, re-opening until I fix it.
```
thread 'main' panicked at 'failed to delete the crate: Unknown(BufferedHttpResponse {status: 400, body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>MalformedXML</Code><Message>The XML you provided was not well-formed or did not validate against our published schema</Message><RequestId>3A0407C0B2410DCE</RequestId><HostId>WA3p1NxP9ZbBH/PyDUlcaLVbYwH3mv1FPC1aCoeV8GJ62YLLcY1AS8C0UfdCjj8H1RhGYCSI21s=</HostId></Error>", headers: {"x-amz-request-id": "3A0407C0B2410DCE", "x-amz-id-2": "WA3p1NxP9ZbBH/PyDUlcaLVbYwH3mv1FPC1aCoeV8GJ62YLLcY1AS8C0UfdCjj8H1RhGYCSI21s=", "content-type": "application/xml", "transfer-encoding": "chunked", "date": "Thu, 16 Jul 2020 14:37:33 GMT", "connection": "close", "server": "AmazonS3"} })

   0: failure::backtrace::internal::InternalBacktrace::new
   1: failure::backtrace::Backtrace::new
   2: cratesfyi::db::delete::delete_prefix_from_s3
   3: cratesfyi::db::delete::delete_version
   4: cratesfyi::CommandLine::handle_args
   5: cratesfyi::main
   6: std::rt::lang_start::{{closure}}
   7: std::rt::lang_start_internal::{{closure}}
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/rt.rs:52
      std::panicking::try::do_call
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:331
      std::panicking::try
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:274
      std::panic::catch_unwind
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/rt.rs:51
   8: main
   9: __libc_start_main
  10: _start
', src/bin/cratesfyi.rs:471:18
```

**Comment by jyn514** [comment]
Clearly my tests in the PR were not good enough.
```
thread 'main' panicked at 'failed to delete the crate: Error(Db(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("23503"), message: "update or delete on table \"releases\" violates foreign key constraint \"compression_rels_release_fkey\" on table \"compression_rels\"", detail: Some("Key (id)=(1) is still referenced from table \"compression_rels\"."), hint: None, position: None, where_: None, schema: Some("public"), table: Some("compression_rels"), column: None, datatype: None, constraint: Some("compression_rels_release_fkey"), file: Some("ri_triggers.c"), line: Some(2476), routine: Some("ri_ReportViolation") }))', src/bin/cratesfyi.rs:471:18
```
Not sure why this didn't show up 🤔

**Comment by jyn514** [comment]
> #893 did not actually work, re-opening until I fix it.

This was just https://github.com/rust-lang/docs.rs/issues/899, nothing to worry about. The actual bug was fixed in https://github.com/rust-lang/docs.rs/pull/896. So this can be closed :)
