### ISSUE TITLE
Intermittent panics in `get_file()`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#572]
Happened twice in the past week, maybe S3 is timing out? Relevant unwraps: https://github.com/rust-lang/docs.rs/blob/master/src/db/file.rs#L86

```
Jan 20 14:53:49 docsrs cratesfyi[29830]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: Error { kind: Body, cause: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" } } }', src/libcore/result.rs:1165:5
Jan 20 14:53:49 docsrs cratesfyi[29830]: stack backtrace:
Jan 20 14:53:49 docsrs cratesfyi[29830]:    0: backtrace::backtrace::libunwind::trace
Jan 20 14:53:49 docsrs cratesfyi[29830]:              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
... snip ...
Jan 20 14:53:49 docsrs cratesfyi[29830]:   14: core::result::unwrap_failed
Jan 20 14:53:49 docsrs cratesfyi[29830]:              at src/libcore/result.rs:1165
Jan 20 14:53:49 docsrs cratesfyi[29830]:   15: cratesfyi::db::file::get_path
Jan 20 14:53:49 docsrs cratesfyi[29830]:   16: cratesfyi::web::rustdoc::rustdoc_html_server_handler
Jan 20 14:53:49 docsrs cratesfyi[29830]:   17: <F as iron::middleware::Handler>::handle
Jan 20 14:53:49 docsrs cratesfyi[29830]:   18: <alloc::boxed::Box<dyn iron::middleware::Handler> as iron::middleware::Handler>::handle
Jan 20 14:53:49 docsrs cratesfyi[29830]:   19: <cratesfyi::web::routes::BlockBlacklistedPrefixes as iron::middleware::Handler>::handle
Jan 20 14:53:49 docsrs cratesfyi[29830]:   20: <alloc::boxed::Box<dyn iron::middleware::Handler> as iron::middleware::Handler>::handle
Jan 20 14:53:49 docsrs cratesfyi[29830]:   21: router::router::Router::handle_method
Jan 20 14:53:49 docsrs cratesfyi[29830]:   22: <router::router::Router as iron::middleware::Handler>::handle
Jan 20 14:53:49 docsrs cratesfyi[29830]:   23: iron::middleware::Chain::continue_from_handler
Jan 20 14:53:49 docsrs cratesfyi[29830]:   24: <iron::middleware::Chain as iron::middleware::Handler>::handle
```

**Comment by jyn514** [comment]
There are other, different panics in the same function. This panic comes from `res.body.unwrap()`, `res.last_modified.unwrap()`, or `res.content_type.unwrap()`  while the one above came from `read_to_end()`.

```
Jan 23 09:44:07 docsrs cratesfyi[32132]: thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
Jan 23 09:44:07 docsrs cratesfyi[32132]: stack backtrace:
Jan 23 09:44:07 docsrs cratesfyi[32132]:    0: backtrace::backtrace::libunwind::trace
Jan 23 09:44:07 docsrs cratesfyi[32132]:              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
... snip ...
Jan 23 09:44:07 docsrs cratesfyi[32132]:   14: core::panicking::panic
Jan 23 09:44:07 docsrs cratesfyi[32132]:              at src/libcore/panicking.rs:70
Jan 23 09:44:07 docsrs cratesfyi[32132]:   15: cratesfyi::db::file::get_path
Jan 23 09:44:07 docsrs cratesfyi[32132]:   16: <cratesfyi::web::file::DatabaseFileHandler as iron::middleware::Handler>::handle
Jan 23 09:44:07 docsrs cratesfyi[32132]:   17: <alloc::boxed::Box<dyn iron::middleware::Handler> as iron::middleware::Handler>::handle
Jan 23 09:44:07 docsrs cratesfyi[32132]:   18: <cratesfyi::web::routes::BlockBlacklistedPrefixes as iron::middleware::Handler>::handle
Jan 23 09:44:07 docsrs cratesfyi[32132]:   19: <alloc::boxed::Box<dyn iron::middleware::Handler> as iron::middleware::Handler>::handle
Jan 23 09:44:07 docsrs cratesfyi[32132]:   20: <cratesfyi::web::CratesfyiHandler as iron::middleware::Handler>::handle
Jan 23 09:44:07 docsrs cratesfyi[32132]:   21: <iron::iron::RawHandler<H> as hyper::server::Handler>::handle
Jan 23 09:44:07 docsrs cratesfyi[32132]:   22: hyper::server::Worker<H>::handle_connection
Jan 23 09:44:07 docsrs cratesfyi[32132]:   23: hyper::server::listener::spawn_with::{{closure}}
```

**Comment by jyn514** [comment]
I haven't seen these panics in a very long time, probably it was some S3 bug that's since been fixed.
