### ISSUE TITLE
Panic/timeout connecting to postgres

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#626]
```
Feb 25 19:38:47 docsrs cratesfyi[29874]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error(None)', src/libcore/result.rs:1165:5
Feb 25 19:38:47 docsrs cratesfyi[29874]: stack backtrace:
Feb 25 19:38:47 docsrs cratesfyi[29874]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error(None)', src/libcore/result.rs:1165:5
Feb 25 19:38:47 docsrs cratesfyi[29874]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error(None)', src/libcore/result.rs:1165:5
Feb 25 19:38:47 docsrs cratesfyi[29874]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error(None)', src/libcore/result.rs:1165:5
...
Feb 25 19:38:48 docsrs cratesfyi[29874]:   14: core::result::unwrap_failed
Feb 25 19:38:48 docsrs cratesfyi[29874]:              at src/libcore/result.rs:1165
Feb 25 19:38:48 docsrs cratesfyi[29874]:   15: <cratesfyi::web::pool::Pool as iron::middleware::BeforeMiddleware>::before
Feb 25 19:38:48 docsrs cratesfyi[29874]:   16: iron::middleware::Chain::continue_from_before
Feb 25 19:38:48 docsrs cratesfyi[29874]:   17: <iron::middleware::Chain as iron::middleware::Handler>::handle
Feb 25 19:38:48 docsrs cratesfyi[29874]:   18: <alloc::boxed::Box<dyn iron::middleware::Handler> as iron::middleware::Handler>::handle
Feb 25 19:38:48 docsrs cratesfyi[29874]:   19: <cratesfyi::web::CratesfyiHandler as iron::middleware::Handler>::handle
Feb 25 19:38:48 docsrs cratesfyi[29874]:   20: <iron::iron::RawHandler<H> as hyper::server::Handler>::handle
Feb 25 19:38:48 docsrs cratesfyi[29874]:   21: hyper::server::Worker<H>::handle_connection
Feb 25 19:38:48 docsrs cratesfyi[29874]:   22: hyper::server::listener::spawn_with::{{closure}}
Feb 25 19:38:48 docsrs cratesfyi[29874]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
...
Feb 25 19:40:34 docsrs cratesfyi[29874]: thread 'thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error(None)', src/libcore/result.rs:<unnamed>' 
Feb 25 19:40:34 docsrs cratesfyi[29874]: 1165:5
Feb 25 19:40:35 docsrs kernel: nginx invoked oom-killer: gfp_mask=0x14200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=0
```

Relevant code: https://github.com/rust-lang/docs.rs/blob/master/src/web/pool.rs#L34

**Comment by jyn514** [comment]
Secondary problem: apparently crates that are fetched but not added to the index will be lost and not build.
