### ISSUE TITLE
Panic while rendering crate/builds.html

### ISSUE THREAD

**Issue by jyn514** [rust-lang/docs.rs#969]
Saw three or four of these in the server logs.

```
Aug 11 23:49:00 docsrs cratesfyi[27117]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Msg("Failed to render \'crate/builds.html\'"), source: Some(Error { kind: Msg("Variable `metadata.name` not found in context while rendering \'crate/builds.html\'"), source: None }) }', src/web/page/web_page.rs:42:24
Aug 11 23:49:00 docsrs cratesfyi[27117]: stack backtrace:
Aug 11 23:49:00 docsrs cratesfyi[27117]:    0: backtrace::backtrace::libunwind::trace
Aug 11 23:49:00 docsrs cratesfyi[27117]:              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
Aug 11 23:49:00 docsrs cratesfyi[27117]:    1: backtrace::backtrace::trace_unsynchronized
Aug 11 23:49:00 docsrs cratesfyi[27117]:              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
Aug 11 23:49:00 docsrs cratesfyi[27117]:    2: std::sys_common::backtrace::_print_fmt
Aug 11 23:49:00 docsrs cratesfyi[27117]:              at src/libstd/sys_common/backtrace.rs:78
Aug 11 23:49:00 docsrs cratesfyi[27117]:    3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
Aug 11 23:49:00 docsrs cratesfyi[27117]:              at src/libstd/sys_common/backtrace.rs:59
Aug 11 23:49:00 docsrs cratesfyi[27117]:    4: core::fmt::write
Aug 11 23:49:00 docsrs cratesfyi[27117]:              at src/libcore/fmt/mod.rs:1069
Aug 11 23:49:00 docsrs cratesfyi[27117]:    5: std::io::Write::write_fmt
Aug 11 23:49:00 docsrs cratesfyi[27117]:              at src/libstd/io/mod.rs:1504
Aug 11 23:49:00 docsrs cratesfyi[27117]:    6: std::sys_common::backtrace::_print
Aug 11 23:49:00 docsrs cratesfyi[27117]:              at src/libstd/sys_common/backtrace.rs:62
Aug 11 23:49:00 docsrs cratesfyi[27117]:    7: std::sys_common::backtrace::print
Aug 11 23:49:00 docsrs cratesfyi[27117]:              at src/libstd/sys_common/backtrace.rs:49
Aug 11 23:49:00 docsrs cratesfyi[27117]:    8: std::panicking::default_hook::{{closure}}
Aug 11 23:49:00 docsrs cratesfyi[27117]:              at src/libstd/panicking.rs:198
Aug 11 23:49:00 docsrs cratesfyi[27117]:    9: std::panicking::default_hook
Aug 11 23:49:00 docsrs cratesfyi[27117]:              at src/libstd/panicking.rs:218
Aug 11 23:49:00 docsrs cratesfyi[27117]:   10: std::panicking::rust_panic_with_hook
Aug 11 23:49:00 docsrs cratesfyi[27117]:              at src/libstd/panicking.rs:511
Aug 11 23:49:00 docsrs cratesfyi[27117]:   11: rust_begin_unwind
Aug 11 23:49:00 docsrs cratesfyi[27117]:              at src/libstd/panicking.rs:419
Aug 11 23:49:00 docsrs cratesfyi[27117]:   12: core::panicking::panic_fmt
Aug 11 23:49:00 docsrs cratesfyi[27117]:              at src/libcore/panicking.rs:111
Aug 11 23:49:00 docsrs cratesfyi[27117]:   13: core::option::expect_none_failed
Aug 11 23:49:00 docsrs cratesfyi[27117]:              at src/libcore/option.rs:1268
Aug 11 23:49:00 docsrs cratesfyi[27117]:   14: <F as iron::middleware::Handler>::handle
Aug 11 23:49:00 docsrs cratesfyi[27117]:   15: <alloc::boxed::Box<dyn iron::middleware::Handler> as iron::middleware::Handler>::handle
Aug 11 23:49:00 docsrs cratesfyi[27117]:   16: <cratesfyi::web::metrics::RequestRecorder as iron::middleware::Handler>::handle
Aug 11 23:49:00 docsrs cratesfyi[27117]:   17: <alloc::boxed::Box<dyn iron::middleware::Handler> as iron::middleware::Handler>::handle
Aug 11 23:49:00 docsrs cratesfyi[27117]:   18: <alloc::boxed::Box<dyn iron::middleware::Handler> as iron::middleware::Handler>::handle
Aug 11 23:49:00 docsrs cratesfyi[27117]:   19: router::router::Router::handle_method
Aug 11 23:49:00 docsrs cratesfyi[27117]:   20: <router::router::Router as iron::middleware::Handler>::handle
Aug 11 23:49:00 docsrs cratesfyi[27117]:   21: iron::middleware::Chain::continue_from_before
Aug 11 23:49:00 docsrs cratesfyi[27117]:   22: <iron::middleware::Chain as iron::middleware::Handler>::handle
Aug 11 23:49:00 docsrs cratesfyi[27117]:   23: <alloc::boxed::Box<dyn iron::middleware::Handler> as iron::middleware::Handler>::handle
Aug 11 23:49:00 docsrs cratesfyi[27117]:   24: <cratesfyi::web::CratesfyiHandler as iron::middleware::Handler>::handle
Aug 11 23:49:00 docsrs cratesfyi[27117]:   25: <iron::iron::RawHandler<H> as hyper::server::Handler>::handle
Aug 11 23:49:00 docsrs cratesfyi[27117]:   26: hyper::server::Worker<H>::handle_connection
Aug 11 23:49:00 docsrs cratesfyi[27117]:   27: hyper::server::listener::spawn_with::{{closure}}
Aug 11 23:49:00 docsrs cratesfyi[27117]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jyn514** [comment]
From some debugging on discord:

> kixiron: looks like we don't call `cexpect` for the builds page
> kixiron: So the entirety of metadata is an Option
> kixiron: I think someone's looking at a builds page that hasn't been built yet?
> kixiron: I can change the unwrap in WebPage::into_response to a ctry

@Kixiron also suggested adding logging to `cexpect` which says _which_ page had an error, not just what the error was.
